### ISSUE TITLE
I'm safe timer

### ISSUE THREAD

**Issue by slightlydiff** [slightlydiff/Look-Out-For-Me-Public#10]
New setting for I'm safe frequency (x = 0 to 120 minutes) and I'm safe cancellation delay (y = 0 to 5 minutes) ;both sliders.

When active an alert will be triggered every x minutes with a grace period of y minutes to cancel before it is actually sent

**Comment by GeorgeTurner** [comment]
That's good, I just updated the app but didn't see these enhancements?

**Comment by slightlydiff** [comment]
You won’t yet.   I have only moved the incomplete issues across to the public repo

Slightly Different Limited

dare to be different



T:	03 541 9468

E:	stephen@slightlydifferent.co.nz <mailto:stephen@slightlydifferent.co.nz>
W:	www.slightlydifferent.co.nz <http://www.slightlydifferent.co.nz/>

please consider the environment before printing this e-mail

147 Trass Valley Road, Wakefield, 7095, New Zealand

Registered in New Zealand No. 2386275
Registered address:  Campbell Thompson Limited, 14 Oxford Street, Richmond, Nelson 7020

.....................................................................................................................................
 This email message is for the use of the addressee only.
 Un-authorized use, dissemination or copying is prohibited.  
 If you are not the addressee please notify the sender immediately.
 Slightly Different Limited cannot accept liability for any errors and omissions.
 Please note that Slightly Different Limited will not accept any responsibility 
    for viruses and it is your responsibility to scan attachments (if any). 
.....................................................................................................................................

**Comment by GeorgeTurner** [comment]
The timer delay doesn't show the countdown any more it just stays on the 'An alert has been sent to your group 'home' status until the timer expires and the alert is actually sent. Is this to be updated in tonight's update? Cheers

**Comment by slightlydiff** [comment]
Initial implementation of intended functionality released for testing

**Comment by GeorgeTurner** [comment]
Timer only works when the app is actually open and running in foreground. If I turn phone onto standby or background the app the timer stops and only starts again from where it left off when you bring it back to the foreground.

**Comment by GeorgeTurner** [comment]
Also need a way to activate the panic button while the timer is going. Always need the option for the panic button.

**Comment by GeorgeTurner** [comment]
Damn may have this on the wrong issue I am talking about the I'm safe timer

**Comment by GeorgeTurner** [comment]
Timer finally went to end of countdown not entirely sure how cos I didn't have the app open and foregrounded. Once the delay timer had finished all went off as it should but then the timer didn't reset for another countdown it just stopped?

**Comment by GeorgeTurner** [comment]
Ok timer seems to countdown but not in the correct time frame and then it goes to the delay timer once I bring the app back to the foreground. Unfortunately this is often 60-90mins later instead of 30mins

**Comment by slightlydiff** [comment]
NOTES;
Remove "Silent Mode" switch in favour of using phones native mute
Move active group selection to radio selection on groups page if possible
Therefore no need for config pane so remove and make panic button always active

**Comment by slightlydiff** [comment]
All notes here have been actions except running the app in background mode which I am moving to a new ticket
