### ISSUE TITLE
Top nav bar styling

### ISSUE THREAD

**Issue by slightlydiff** [slightlydiff/Look-Out-For-Me-Public#11]
Make the top nav bar background dark grey

**Comment by GeorgeTurner** [comment]
Steve can you make that a mid grey colour - taking what it is now as a dark grey? Just wonder if the top info bar would look better that way. Cheers

**Comment by slightlydiff** [comment]
I tried that last night but you loose the contrast in the text.  So I have just made it as light as I dare.  See what you think and close this ticket if that's OK.

**Comment by GeorgeTurner** [comment]
Yip that's much better thanks.
