### ISSUE TITLE
Return from settings

### ISSUE THREAD

**Issue by slightlydiff** [slightlydiff/Look-Out-For-Me-Public#17]
Also the settings options goes to the settings app but then it seems to need two panes to get back to the app - screenshot attached. 

If you click on the top link it goes straight back to the app but if you use the second link down with the big 'Settings' it goes into the apple settings app and from there you either have to go back to the lofm app or click on 'Back to Look Out Fo....' To go back to the lofm app. 
![image1](https://cloud.githubusercontent.com/assets/1666768/10037143/1489cd2c-6206-11e5-9530-4d2c54af42d5.PNG)

**Comment by slightlydiff** [comment]
I have looked into this.  Prior to IOS 9 once you were in Apples Settings.app you couldn't navigate back to the app you were in.  You had to click the home button to close Settings.app and then open the app you were in again.

As of IOS 9 they have now introduced a link direct back to the app your were in.  It is small and above the < Settings link which links back up into the main settings page (like IOS 8 and before) but it is at least there which is a big improvement.

We have no control over this link or the styling of it as it is part of Apple IOS.

**Comment by GeorgeTurner** [comment]
All good yes found this is an apple thing nothing to do with the app!
