### ISSUE TITLE
Alerts 

### ISSUE THREAD

**Issue by GeorgeTurner** [slightlydiff/Look-Out-For-Me-Public#20]
Steve do we need to have an alert come up when the panic button is pushed ie An alert has been sent to your group 'Home' could that be intergrated into the help button screen ie just below 'Cancel Alert' where you have additional information when the timer delay feature is used. Just seems a neater less intrusive way of getting the information there when the user is ready to see it. Cheers

**Comment by slightlydiff** [comment]
I've now changed this to display in the cancel button

**Comment by GeorgeTurner** [comment]
Very nice implementation Steve that's all good
