### ISSUE TITLE
Panic timer delay

### ISSUE THREAD

**Issue by GeorgeTurner** [slightlydiff/Look-Out-For-Me-Public#28]
Once using the delay feature for the panic button it counts down correctly once and once the alert message switches to your alert has been sent to you group etc etc it doesn't reset the next time you click help to start the timer again. The timer counts down correctly and vibrates just like it should but the message doesn't change from your alert has been sent. I don't get the timer again.

**Comment by GeorgeTurner** [comment]
![image](https://cloud.githubusercontent.com/assets/14720428/10360725/49b3ea3c-6dff-11e5-8af0-8bcb871ed111.png)

**Comment by slightlydiff** [comment]
The latest drop box is an interim build to bring in two new plugins but the code is not complete so not worthy of testing yet

**Comment by GeorgeTurner** [comment]
Right all good still very much like the new look!

All the best
George

www.georgeturner.co.nz
021 876 303
03 391 0019

On 8/10/2015, at 21:13, Stephen Smith <notifications@github.com> wrote:

The latest drop box is an interim build to bring in two new plugins but the code is not complete so not worthy of testing yet

**Comment by slightlydiff** [comment]
Not an issue as was tested on interim build so closing for now subject to further testing
