### ISSUE TITLE
Double shake activation

### ISSUE THREAD

**Issue by GeorgeTurner** [slightlydiff/Look-Out-For-Me-Public#29]
If I activate the panic delay timer I can get multiple activations using the shake function. Only works if the delay timer is running otherwise no bug. Bug shows if the help button is pressed and then the device is shaken. Once multiple alerts are active it is impossible to turn off second alert.  Can also shake to start alert and then shake again gets second alert. Need to hold alerts once activated.

**Comment by slightlydiff** [comment]
Fixed 15.10.15 and testing consistently safe now so closing but would like to re-test before release
