### ISSUE TITLE
Interaction between shake to alert and shake doing IOS events

### ISSUE THREAD

**Issue by slightlydiff** [slightlydiff/Look-Out-For-Me-Public#3]
I'm getting an interesting interaction between the copy and paste function (used that to paste in the email address) and the shake to alert option. 

Sometimes I get the alert sometimes the copy undo function. 

This is the same as the other reported Redo popup

? Stop events bubbling ?

**Comment by slightlydiff** [comment]
I'm struggling to replicate this issue. If when you test tonight you still get it can you please let me have a blow by blow account of what you have to do to replicate it.

**Comment by GeorgeTurner** [comment]
I'm trying this and I get an error message all the time. The app is sensitive now so that part is good but I presume that the error is something you are working on

**Comment by GeorgeTurner** [comment]
![image](https://cloud.githubusercontent.com/assets/14720428/10180668/b9d72d0a-676b-11e5-8a97-3fe610ed515d.png)

**Comment by slightlydiff** [comment]
That's an interim build where I have changed a function name in one part but not another so the last message is not an issue but just blocks testing for the moment

**Comment by GeorgeTurner** [comment]
Right all good I'll wait till the next Dropbox release. Cheers

**Comment by GeorgeTurner** [comment]
Seems like if I gently shake the device slowly I get the native iOS interaction but if I shake it a bit harder and more forcefully I get the app coming through? The app seems to be working well now with the shake option.

**Comment by GeorgeTurner** [comment]
Stil testing this and the app is picking up the interaction nicely almost all of the time. Seems this one is looking good now
