### ISSUE TITLE
Error on copy and paste email address

### ISSUE THREAD

**Issue by slightlydiff** [slightlydiff/Look-Out-For-Me-Public#4]
See screen shot in email 19th Sept 9:42am from George where nativePageTransition code can't find element "a"

**Comment by slightlydiff** [comment]
![image1](https://cloud.githubusercontent.com/assets/1666768/10037113/aa752116-6205-11e5-9532-ee948fced39f.PNG)

**Comment by slightlydiff** [comment]
This is now resolved.  Built in transitions library has a bug which I have fixed and reported back to Telerik

**Comment by GeorgeTurner** [comment]
Seriously you should have a consultancy fee out of all this with them....

All the best
George

www.georgeturner.co.nz
021 876 303
03 391 0019

On 29/09/2015, at 12:53, Stephen Smith <notifications@github.com> wrote:

This is now resolved. Built in transitions library has a bug which I have fixed and reported back to Telerik
