### ISSUE TITLE
Help button not showing on return to view

### ISSUE THREAD

**Issue by slightlydiff** [slightlydiff/Look-Out-For-Me-Public#5]
If you go to the main screen then turn the help button on then go to the groups page and then return to the main screen the help button is now not showing but the toggle switch is still on. See screen shot. I have to turn the toggle button off then on again to get it to work again.

**Comment by GeorgeTurner** [comment]
Yeah still doing that at moment.

**Comment by slightlydiff** [comment]
This is now resolved.

Worth testing but I don't think it will work correctly until you have installed the latest version via iTunes.  If you can access iTiunes somewhere let me know and I'll drop box the latest compiled version

**Comment by GeorgeTurner** [comment]
Yes please send it over and I will look to connect through my laptop

All the best
George

www.georgeturner.co.nz
021 876 303
03 391 0019

On 24/09/2015, at 18:14, Stephen Smith <notifications@github.com> wrote:

This is now resolved.

Worth testing but I don't think it will work correctly until you have installed the latest version via iTunes. If you can access iTiunes somewhere let me know and I'll drop box the latest compiled version
