### ISSUE TITLE
Auto login

### ISSUE THREAD

**Issue by slightlydiff** [slightlydiff/Look-Out-For-Me-Public#8]
Add a switch option to enable auto login which, when enabled, will auto lofin if credentials are saved and take you to the panic button if a group is already selected as active

**Comment by GeorgeTurner** [comment]
Nice looking forward to seeing that too

**Comment by slightlydiff** [comment]
This is now added BUT the three finger update won't work for this as it has required some underlying code to be changed which requires a recompile and redistribution.

This is true any time I have to change any project settings, include a new plugin or change any OS specific configuration files such as the Root.plist file to determine Apple iOS settings.app config
